In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
pip install tensorboardX

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 2.4 MB/s eta 0:00:00


### Train LightGCN model

In [ ]:
%cd /content/drive/MyDrive/github/LightGCN_PyTorch/code


/content/drive/MyDrive/github/LightGCN_PyTorch/code


In [ ]:
# reference codes: https://github.com/gusye1234/LightGCN-PyTorch
%run main.py --decay=1e-4 --lr=0.001 --layer=3 --seed=2020 --dataset="yelp2018" --topks="[20]" --recdim=64 --epochs=500

Cpp extension not loaded
>>SEED: 2020
loading [../data/yelp2018]
1237259 interactions for training
324147 interactions for testing
yelp2018 Sparsity : 0.0012958757851778647
yelp2018 is ready to go
===========config================
{'A_n_fold': 100,
 'A_split': False,
 'bigdata': False,
 'bpr_batch_size': 2048,
 'decay': 0.0001,
 'dropout': 0,
 'keep_prob': 0.6,
 'latent_dim_rec': 64,
 'lightGCN_n_layers': 3,
 'lr': 0.001,
 'multicore': 0,
 'pretrain': 0,
 'test_u_batch_size': 100}
cores for test: 6
comment: lgn
tensorboard: 1
LOAD: 0
Weight path: ./checkpoints
Test Topks: [20]
using bpr loss
===========end===================
use NORMAL distribution initilizer
loading adjacency matrix
successfully loaded...
don't split the matrix
lgn is already to go(dropout:0)
load and save to /content/drive/MyDrive/github/LightGCN_PyTorch/code/checkpoints/lgn-yelp2018-3-64.pth.tar
[TEST]
{'precision': array([0.00027788]), 'recall': array([0.00052693]), 'ndcg': array([0.00044859])}
EPOCH[1/500] loss0.4

In [ ]:
# Save user and item embeddings for Gan model pretraining

#np.save(user_emb_file, Recmodel.embedding_user.weight.data.cpu().numpy())
#np.save(item_emb_file, Recmodel.embedding_item.weight.data.cpu().numpy())

#user_emb_file = "user_emb.npy"
#item_emb_file = "item_emb.npy"

#world.config['user_emb'] = np.load(user_emb_file)
#world.config['item_emb'] = np.load(item_emb_file)


In [ ]:
import numpy as np
import os
# Create a folder to store the embeddings
#embedding_folder = "embeddings"
#os.makedirs(embedding_folder, exist_ok=True)

# Get the user and item embeddings from the trained model
#user_embeddings = Recmodel.embedding_user.weight.data.cpu().numpy()
#item_embeddings = Recmodel.embedding_item.weight.data.cpu().numpy()

# Save the embeddings to files
#user_emb_file = os.path.join(embedding_folder, "user_embeddings.npy")
#item_emb_file = os.path.join(embedding_folder, "item_embeddings.npy")
#np.save(user_emb_file, user_embeddings)
#np.save(item_emb_file, item_embeddings)


In [ ]:
user_embeddings = Recmodel.embedding_user.weight.data
item_embeddings = Recmodel.embedding_item.weight.data

In [ ]:
user_embeddings.shape

torch.Size([31668, 64])

In [ ]:
item_embeddings.shape

torch.Size([38048, 64])

In [ ]:
Recmodel_load.eval()

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-1e35e5984140>", line 1, in <cell line: 1>
    Recmodel_load.eval()
NameError: name 'Recmodel_load' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'NameError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.10/dist-packages/IPython/co

In [ ]:
# prediction
users = torch.tensor([15,29,198,477])
ratings = Recmodel.getUsersRating(users)

In [ ]:
ratings

tensor([[0.9424, 0.9998, 1.0000,  ..., 0.4628, 0.3536, 0.3386],
        [1.0000, 0.8888, 0.9645,  ..., 0.3120, 0.1965, 0.3228],
        [1.0000, 0.8833, 0.9627,  ..., 0.3673, 0.1872, 0.3467],
        [0.6682, 0.7741, 0.7744,  ..., 0.5333, 0.4170, 0.4374]],
       device='cuda:0', grad_fn=<SigmoidBackward0>)

In [ ]:
# recommend top 20 items
top_ratings, top_indices = torch.topk(ratings, 20, dim=1, largest=True)

In [ ]:
top_indices

tensor([[ 7270,  3410,   932,  8136,  4983,  3407,  8129,   949,     2,  4059,
          4039,   951,   947,  4048,  3401,   948,  4984,  4044,   953,  3397],
        [ 3245,   649,    81,    87,    11,     0,    12,    15,   783,   774,
           710,   773,  2012,   786,  2014,  2902,   657,     8,   762,   769],
        [  786,   710,  2014,  2902,   783,   649,   657,    12,    11,    81,
            87,    15,     0,  3245,  2012,   774,   773,   769,  1540,   762],
        [ 6351,  5030,  8106,  3206,  8109,   754,  8517,  5883,  9873,  7859,
           745,  6348,  6335,  6332,  6336, 12220,  5899, 10000,  8523,  9991]],
       device='cuda:0')

### Train GAN model

In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import os
import matplotlib.pyplot as plt

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-efc5ffbf02b1>", line 1, in <cell line: 1>
    import tensorflow as tf
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1002, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 945, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1439, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1366, in _path_importer_cache
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2099, in showtrace

In [ ]:
%cd /content/drive/MyDrive/github/LightGCN_PyTorch/code/embeddings

/content/drive/MyDrive/github/LightGCN_PyTorch/code/embeddings


In [ ]:

device = tf.device('GPU' if tf.config.list_physical_devices('cuda:0') else 'CPU:0')

In [ ]:
# Load pre-trained gan model
gan = tf.keras.models.load_model('gan.h5')
with device:
  gan

In [ ]:
from tensorflow.keras.layers import Input, Dense, Reshape, Flatten
from tensorflow.keras.layers import BatchNormalization, Activation, ZeroPadding2D
from tensorflow.keras.layers import LeakyReLU
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Sequential, Model

# Define the generator
def build_generator(latent_dim, output_shape):
    model = Sequential()
    model.add(Dense(128, input_dim=latent_dim))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(512))
    model.add(LeakyReLU(alpha=0.2))
    model.add(BatchNormalization(momentum=0.8))
    model.add(Dense(output_shape, activation='tanh'))
    model.summary()

    noise = Input(shape=(latent_dim,))
    img = model(noise)

    return Model(noise, img)

# Define the discriminator
def build_discriminator(input_shape):
    model = Sequential()
    model.add(Dense(512, input_shape=input_shape))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(256))
    model.add(LeakyReLU(alpha=0.2))
    model.add(Dense(1, activation='sigmoid'))
    model.summary()

    img = Input(shape=input_shape)
    validity = model(img)

    return Model(img, validity)

# Define the GAN model
def build_gan(generator, discriminator):
    discriminator.trainable = False

    gan_input = Input(shape=(latent_dim,))
    generated_img = generator(gan_input)
    gan_output = discriminator(generated_img)

    gan = Model(gan_input, gan_output)
    gan.compile(loss='binary_crossentropy', optimizer=Adam(0.0002, 0.5))

    return gan

In [ ]:
# hyper-parameters
latent_dim = 64
reg_lambda = 0.01
epochs = 100
batch_size = 64
learning_rate = 0.001 #0.001

In [ ]:
# Build the generator and discriminator
latent_dim = user_embeddings.shape[1]
output_shape = item_embeddings.shape[1]
generator = build_generator(latent_dim, output_shape)
discriminator = build_discriminator(input_shape=(output_shape,))

# Build the GAN model
with device:
  gan = build_gan(generator, discriminator)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               8320      
                                                                 
 leaky_re_lu (LeakyReLU)     (None, 128)               0         
                                                                 
 batch_normalization (BatchN  (None, 128)              512       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 256)               33024     
                                                                 
 leaky_re_lu_1 (LeakyReLU)   (None, 256)               0         
                                                                 
 batch_normalization_1 (Batc  (None, 256)              1024      
 hNormalization)                                        

In [ ]:
# Generate synthetic data using the GAN model
n_samples = 10000
latent_dim = 64
with device:
  synthetic_item_embeddings = generator.predict(np.random.normal(0, 1, size=(n_samples, latent_dim)))
  synthetic_item_embeddings = torch.from_numpy(synthetic_item_embeddings)

313/313 [==============================] - 1s 2ms/step


In [ ]:
device2 = torch.device("cuda:0")  # or "cpu" if you want to move it to the CPU
synthetic_item_embeddings = synthetic_item_embeddings.to(device2)

In [ ]:
print("Tensor Device:", item_embeddings.device)

Tensor Device: cuda:0


In [ ]:
print("Tensor Device:", synthetic_item_embeddings.device)

Tensor Device: cuda:0


In [ ]:
combined_item_embeddings = torch.cat((item_embeddings, synthetic_item_embeddings), dim=0)


In [ ]:
combined_item_embeddings.shape

torch.Size([48048, 64])

### LigthGCN Prediction by using sythetic embeddings from GAN


In [ ]:
users = torch.tensor([15,29,198,477])
new_user_embeddings = Recmodel.embedding_user.weight[users.long()]


In [ ]:
new_user_embeddings.shape

torch.Size([4, 64])

In [ ]:
# Calculate ratings for new users
device = torch.device("cuda:0")
new_user_embeddings = new_user_embeddings.to(device)
combined_item_embeddings = combined_item_embeddings.to(device)
new_ratings = torch.matmul(new_user_embeddings, combined_item_embeddings.t())

In [ ]:
# Calculate ratings for new users with sythetic items
device = torch.device("cuda:0")
new_user_embeddings = new_user_embeddings.to(device)
synthetic_item_embeddings = synthetic_item_embeddings.to(device)
new_ratings_sythetic = torch.matmul(new_user_embeddings, synthetic_item_embeddings.t())

In [ ]:
new_ratings_sythetic.shape

torch.Size([4, 10000])

In [ ]:
ratings.shape

torch.Size([4, 38048])

In [ ]:
new_top_ratings, new_top_indices = torch.topk(new_ratings, 20, dim=1, largest=True)

In [ ]:
new_top_ratings, new_top_indices = torch.topk(new_ratings_sythetic, 20, dim=1, largest=True)

In [ ]:
new_top_indices

tensor([[5985, 4298, 7419, 4635, 2588, 8376, 2254, 1644, 6036,  689, 4552, 8957,
         9268, 4123, 3312, 6584, 5886, 2367, 9860, 9087],
        [7688, 8738, 5247, 4568, 3345, 4247, 2747, 2540, 6503, 5465, 2805, 1186,
         6922, 9855,  949, 5576,  254, 3577, 2703, 4748],
        [4568, 4247, 6503, 6922, 7688, 1186, 2540, 3345, 4285, 7312, 5247, 8071,
         5465, 9477, 2747,  254, 7169, 2204, 7632, 7942],
        [9429, 6025, 4942, 3250, 1065, 2191, 9499, 3301, 5795,  763, 6625, 6486,
         2335, 2385, 4988, 1862, 3113, 7963, 9650, 6588]], device='cuda:0')

In [ ]:
top_indices

tensor([[ 7270,  3410,   932,  8136,  4983,  3407,  8129,   949,     2,  4059,
          4039,   951,   947,  4048,  3401,   948,  4984,  4044,   953,  3397],
        [ 3245,   649,    81,    87,    11,     0,    12,    15,   783,   774,
           710,   773,  2012,   786,  2014,  2902,   657,     8,   762,   769],
        [  786,   710,  2014,  2902,   783,   649,   657,    12,    11,    81,
            87,    15,     0,  3245,  2012,   774,   773,   769,  1540,   762],
        [ 6351,  5030,  8106,  3206,  8109,   754,  8517,  5883,  9873,  7859,
           745,  6348,  6335,  6332,  6336, 12220,  5899, 10000,  8523,  9991]],
       device='cuda:0')

### Evalute Recommended Sythetic Items

In [ ]:
top_synthetic_item_embeddings = synthetic_item_embeddings[new_top_indices]

In [ ]:
top_item_embeddings = item_embeddings[top_indices]

In [ ]:
# measure cosnie similartiy between sythetic items with real item for each user
import torch.nn.functional as F
cosine_similarity = {}
# Calculate cosine similarity between top_item_embeddings and top_sythetic_item_embeddings
for i in range(len(users)):
  cosine_similarity[i] = F.cosine_similarity(top_item_embeddings[i], top_synthetic_item_embeddings[i], dim=-1)




In [ ]:
cosine_similarity

tensor([0.3034, 0.2527, 0.3630, 0.3500, 0.2799, 0.3195, 0.2672, 0.3073, 0.3708,
        0.3883, 0.2894, 0.3607, 0.3042, 0.2429, 0.2279, 0.4176, 0.2925, 0.3798,
        0.3569, 0.2631], device='cuda:0')

In [ ]:
import numpy as np
from scipy.stats import ttest_ind



group1 = top_item_embeddings_cpu[3]
group2 = top_sythetic_item_embeddings_cpu[3]

# Calculate the mean difference between pairs of data points
mean_diff = np.mean(group1 - group2, axis=1)

# Perform the independent t-test
t_statistic, p_value = ttest_ind(group1, group2, axis=1, alternative='two-sided')

# Print the results
print("Independent T-Test")
print("T-Statistic:", t_statistic)
print("P-Value:", p_value)

# Compare p-value with significance level (e.g., 0.05)
alpha = 0.05
alpha_corrected = alpha / len(p_value)

if any(p < alpha_corrected for p in p_value):
    print("Reject the null hypothesis: Significant difference between groups.")
else:
    print("Fail to reject the null hypothesis: No significant difference between groups.")

Independent T-Test
T-Statistic: [-0.7569377  -1.3764488  -1.4125736  -0.57883394 -1.035593   -0.61303836
 -0.93740636 -1.3179672  -0.85058254 -0.63808537 -1.6545395  -0.9795325
 -0.20907252 -0.7434321  -1.6170142  -1.384371   -1.3729738  -1.6094289
 -0.642996   -1.593205  ]
P-Value: [0.4505003  0.17112389 0.1602464  0.56373453 0.3023755  0.54095596
 0.3503429  0.18990576 0.3966148  0.52457607 0.10050694 0.32919398
 0.83472925 0.4586041  0.10837613 0.16869175 0.17219904 0.11002523
 0.5213951  0.11361978]
Fail to reject the null hypothesis: No significant difference between groups.
